"""
app.py — StyleKart Customer Intelligence Dashboard (Streamlit)
================================================================
Starter template with all 5 pages structured.
Run: streamlit run app.py

All data is loaded from data/processed/ (generated by run_analysis.py).
All chart functions are in utils/visualizations.py.
"""

import streamlit as st
import pandas as pd
import numpy as np
import os
import json

# --- Page config (must be first Streamlit command) ---
st.set_page_config(
    page_title="StyleKart — Customer Intelligence",
    page_icon="🛍️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- Paths ---
DATA_DIR = os.path.join(os.path.dirname(__file__), "data", "processed")
MODEL_DIR = os.path.join(os.path.dirname(__file__), "models")

# --- Imports (after path setup) ---
from utils.visualizations import *
from utils.rfm import get_recommendations, CAMPAIGN_RECOMMENDATIONS
from utils.churn import business_impact_calculator, RETENTION_ACTIONS


# ====================================================================
# DATA LOADING (cached)
# ====================================================================
@st.cache_data
def load_master_table():
    return pd.read_csv(os.path.join(DATA_DIR, "master_customer_table.csv"))

@st.cache_data
def load_rfm():
    return pd.read_csv(os.path.join(DATA_DIR, "rfm_scored.csv"))

@st.cache_data
def load_segment_summary():
    return pd.read_csv(os.path.join(DATA_DIR, "segment_summary.csv"))

@st.cache_data
def load_clv():
    # Try statistical first, fall back to features
    path_stat = os.path.join(DATA_DIR, "clv_statistical.csv")
    path_feat = os.path.join(DATA_DIR, "clv_features.csv")
    if os.path.exists(path_stat):
        return pd.read_csv(path_stat)
    return pd.read_csv(path_feat)

@st.cache_data
def load_churn_predictions():
    return pd.read_csv(os.path.join(DATA_DIR, "churn_predictions.csv"))

@st.cache_data
def load_cleaning_report():
    with open(os.path.join(DATA_DIR, "cleaning_report.json")) as f:
        return json.load(f)

@st.cache_data
def load_cohort():
    return pd.read_csv(os.path.join(DATA_DIR, "cohort_retention.csv"), index_col=0)

@st.cache_data
def load_hypothesis_results():
    with open(os.path.join(DATA_DIR, "hypothesis_results.json")) as f:
        return json.load(f)

@st.cache_data
def load_budget_analysis():
    return pd.read_csv(os.path.join(DATA_DIR, "budget_analysis.csv"))

@st.cache_data
def load_priority_50():
    return pd.read_csv(os.path.join(DATA_DIR, "priority_top_50.csv"))

@st.cache_data
def load_clean_transactions():
    df = pd.read_csv(os.path.join(DATA_DIR, "cleaned_transactions.csv"))
    df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
    return df

@st.cache_data
def load_threshold_sweep():
    return pd.read_csv(os.path.join(DATA_DIR, "threshold_sweep.csv"))


# ====================================================================
# SIDEBAR
# ====================================================================
with st.sidebar:
    st.image("https://via.placeholder.com/200x60?text=StyleKart", width=200)
    st.title("StyleKart Intelligence")
    st.markdown("---")

    page = st.radio(
        "Navigate",
        ["📊 Overview & EDA", "🎯 RFM Segmentation", "💰 CLV Prediction",
         "⚠️ Churn Prediction", "🔗 Integrated Dashboard"],
        index=0,
    )

    st.markdown("---")

    # Date filter (global)
    # TODO: Load df_clean, add date range filter here
    # df_clean = load_clean_transactions()
    # min_date, max_date = df_clean["InvoiceDate"].min(), df_clean["InvoiceDate"].max()
    # date_range = st.date_input("Date Range", [min_date, max_date])

    with st.expander("ℹ️ About"):
        st.markdown("""
        **SBR Session 5 — Customer Segmentation**
        
        Dataset: Online Retail II (UCI, 2009–2011)  
        Market: United Kingdom (proxy for India)  
        Currency: GBP (×105 ≈ INR)
        
        **Limitations:**
        - UK general retail, not Indian fashion
        - No demographic data
        - ~25% records dropped (null CustomerID)
        """)


# ====================================================================
# PAGE 0: OVERVIEW & EDA
# ====================================================================
if page == "📊 Overview & EDA":
    st.title("📊 Overview & Exploratory Data Analysis")

    # --- KPI Cards ---
    # TODO: Load eda_stats or compute from cleaned data
    master = load_master_table()
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Customers", f"{len(master):,}")
    col2.metric("Total Revenue", f"£{master['Monetary'].sum():,.0f}")
    col3.metric("Avg Order Value", f"£{master['Monetary'].mean():,.0f}")
    col4.metric("Date Range", "2009–2011")

    st.markdown("---")

    # --- Company Context ---
    with st.expander("🏢 StyleKart — Company Profile", expanded=True):
        st.markdown("""
        | Attribute | Detail |
        |-----------|--------|
        | Category | Fashion, Accessories, Lifestyle |
        | Registered Users | ~50,000 |
        | Monthly Orders | ~8,000 |
        | AOV | ₹1,200 |
        | Return Rate | ~18% |
        | Loyalty Program | StyleKart Insider (Bronze/Silver/Gold) |
        """)

    # --- EDA Charts ---
    st.subheader("Monthly Revenue Trend")
    # TODO: Generate from df_clean or load pre-computed
    # fig = plot_monthly_revenue(monthly_revenue_df)
    # st.plotly_chart(fig, use_container_width=True)
    st.info("💡 Load cleaned_transactions.csv and use plot_monthly_revenue()")

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Order Frequency")
        st.info("💡 Use plot_order_frequency_dist()")
    with col2:
        st.subheader("Revenue by Day of Week")
        st.info("💡 Use plot_revenue_by_dow()")

    st.subheader("Cohort Retention Heatmap")
    try:
        cohort = load_cohort()
        fig = plot_cohort_heatmap(cohort)
        st.plotly_chart(fig, use_container_width=True)
    except Exception as e:
        st.warning(f"Cohort data not found: {e}")

    # --- Cleaning report ---
    with st.expander("🔧 Data Quality Summary"):
        try:
            report = load_cleaning_report()
            for k, v in report.items():
                st.write(f"**{k}:** {v}")
        except:
            st.info("Run run_analysis.py first to generate cleaning report.")


# ====================================================================
# PAGE 1: RFM SEGMENTATION
# ====================================================================
elif page == "🎯 RFM Segmentation":
    st.title("🎯 Problem 1 — RFM Customer Segmentation")

    rfm = load_rfm()
    seg_summary = load_segment_summary()

    # --- Hypothesis ---
    with st.expander("📋 Hypothesis H1"):
        try:
            hyp = load_hypothesis_results()["H1"]
            st.write(f"**Top 20% revenue contribution:** {hyp['top_20_revenue_pct']}% "
                     f"({'✅ Validated' if hyp['h1_revenue_validated'] else '❌ Not validated'})")
            st.write(f"**At Risk segment size:** {hyp['at_risk_pct']}% "
                     f"({'✅ Validated' if hyp['h1_at_risk_validated'] else '❌ Not validated'})")
        except:
            st.info("Run analysis first.")

    # --- Filters ---
    segments = st.multiselect(
        "Filter by Segment",
        options=rfm["Segment"].unique(),
        default=rfm["Segment"].unique(),
    )
    filtered_rfm = rfm[rfm["Segment"].isin(segments)]

    # --- Charts ---
    col1, col2 = st.columns(2)
    with col1:
        st.plotly_chart(plot_segment_distribution(filtered_rfm), use_container_width=True)
    with col2:
        st.plotly_chart(plot_segment_revenue_contribution(seg_summary[seg_summary["Segment"].isin(segments)]),
                        use_container_width=True)

    st.plotly_chart(plot_segment_characteristics(seg_summary[seg_summary["Segment"].isin(segments)]),
                    use_container_width=True)
    st.plotly_chart(plot_rfm_scatter(filtered_rfm), use_container_width=True)

    # --- Campaign Recommendations ---
    st.subheader("💡 Campaign Recommendations")
    for seg in segments:
        rec = get_recommendations(seg)
        with st.expander(f"{seg} — {rec['strategy']}"):
            for action in rec["actions"]:
                st.write(f"• {action}")
            st.write(f"**Channel:** {rec['channel']}")
            st.write(f"**Discount:** {rec['discount']}")

    # --- Download ---
    st.download_button(
        "📥 Download RFM Table",
        filtered_rfm.to_csv(index=False),
        "rfm_customers.csv",
        "text/csv",
    )


# ====================================================================
# PAGE 2: CLV PREDICTION
# ====================================================================
elif page == "💰 CLV Prediction":
    st.title("💰 Problem 2 — Customer Lifetime Value Prediction")

    master = load_master_table()

    # --- Hypothesis ---
    with st.expander("📋 Hypothesis H2"):
        try:
            hyp = load_hypothesis_results()["H2"]
            st.write(f"**Unprofitable at CAC ₹380:** {hyp['unprofitable_pct']}% "
                     f"({'✅ Validated' if hyp['h2_validated'] else '❌ Not validated'})")
        except:
            st.info("Run analysis first.")

    # --- Charts ---
    col1, col2 = st.columns(2)
    with col1:
        st.plotly_chart(plot_clv_distribution(master, "predicted_clv"), use_container_width=True)
    with col2:
        st.plotly_chart(plot_revenue_concentration_curve(master, "predicted_clv"), use_container_width=True)

    st.plotly_chart(plot_clv_by_rfm_segment(master, "predicted_clv"), use_container_width=True)

    # --- Budget Calculator ---
    st.subheader("🧮 Budget Calculator")
    cac_input = st.number_input("Customer Acquisition Cost (₹)", value=380, step=10)
    try:
        budget = load_budget_analysis()
        st.dataframe(budget, use_container_width=True)
    except:
        st.info("Run analysis first to generate budget data.")

    # --- Download ---
    st.download_button(
        "📥 Download CLV Table",
        master[["CustomerID", "predicted_clv", "CLV_Tier"]].to_csv(index=False),
        "clv_customers.csv",
        "text/csv",
    )


# ====================================================================
# PAGE 3: CHURN PREDICTION
# ====================================================================
elif page == "⚠️ Churn Prediction":
    st.title("⚠️ Problem 3 — Customer Churn Prediction")

    churn_preds = load_churn_predictions()

    # --- Hypothesis ---
    with st.expander("📋 Hypothesis H3"):
        try:
            hyp = load_hypothesis_results()["H3"]
            st.write(f"**Single-purchase churn rate:** {hyp['single_purchase_churn_rate']}% "
                     f"({'✅ Validated' if hyp['h3_churn_validated'] else '❌ Not validated'})")
            st.write(f"**Best model AUC:** {hyp['best_auc']}")
            st.write(f"**Top 5 features:** {', '.join(hyp['top_5_features'])}")
        except:
            st.info("Run analysis first.")

    # --- Threshold Slider ---
    threshold = st.slider("Churn Probability Threshold", 0.0, 1.0, 0.5, 0.05)

    # --- Churn distribution ---
    st.plotly_chart(plot_churn_probability_dist(churn_preds), use_container_width=True)

    # --- TODO: Load ROC curve data, feature importance from model results ---
    # These require loading the model and test data; integrate as needed
    st.info("💡 Load model from models/ and use plot_roc_curve(), plot_feature_importance(), plot_confusion_matrix()")

    # --- Business Impact Section ---
    st.subheader("📊 Business Impact Calculator")
    st.markdown(f"""
    At threshold **{threshold}**:
    - Customers flagged as churners: **{(churn_preds['churn_probability'] >= threshold).sum():,}**
    - Customers flagged as retained: **{(churn_preds['churn_probability'] < threshold).sum():,}**
    """)

    # --- Retention Actions ---
    st.subheader("🎯 Retention Action Matrix")
    for band, action in RETENTION_ACTIONS.items():
        count = (churn_preds["churn_risk_band"] == band).sum()
        st.write(f"**{band}** ({count:,} customers): {action['action']}")

    # --- Download ---
    st.download_button(
        "📥 Download Churn Predictions",
        churn_preds.to_csv(index=False),
        "churn_predictions.csv",
        "text/csv",
    )


# ====================================================================
# PAGE 4: INTEGRATED DASHBOARD
# ====================================================================
elif page == "🔗 Integrated Dashboard":
    st.title("🔗 Integrated Customer Intelligence Framework")
    st.markdown("""
    > *"This is not three models. This is one decision-making framework."*
    """)

    master = load_master_table()

    # --- KPI Cards ---
    col1, col2, col3, col4 = st.columns(4)
    high_risk = master[master["Churn_Risk_Band"].isin(["High", "Critical"])]
    col1.metric("Total Customers", f"{len(master):,}")
    col2.metric("High/Critical Churn Risk", f"{len(high_risk):,}")
    col3.metric("Revenue at Risk", f"£{high_risk['predicted_clv'].sum():,.0f}")
    col4.metric("Platinum Customers", f"{(master['CLV_Tier'] == 'Platinum').sum():,}")

    st.markdown("---")

    # --- Integrated Bubble Chart ---
    st.plotly_chart(plot_integrated_heatmap(master), use_container_width=True)

    # --- Revenue at Risk ---
    st.plotly_chart(plot_revenue_at_risk(master), use_container_width=True)

    # --- Cross-Problem Insights ---
    st.subheader("🔑 Cross-Problem Insights")

    insight_col1, insight_col2 = st.columns(2)
    with insight_col1:
        hp = master[(master["RFM_Segment"] == "At Risk") &
                     (master["CLV_Tier"].isin(["Platinum", "Gold"])) &
                     (master["Churn_Risk_Band"].isin(["High", "Critical"]))]
        st.metric("🚨 Highest Priority (At Risk + High CLV + High Churn)",
                  f"{len(hp)} customers — £{hp['predicted_clv'].sum():,.0f} at risk")

    with insight_col2:
        lg = master[(master["RFM_Segment"].isin(["Lost", "Hibernating"])) &
                     (master["CLV_Tier"] == "Bronze") &
                     (master["Churn_Risk_Band"].isin(["High", "Critical"]))]
        st.metric("🛑 Let Go (Low CLV + High Churn)", f"{len(lg)} customers — stop spending")

    # --- Priority Action List ---
    st.subheader("📋 Top 50 Priority Customers")
    try:
        top_50 = load_priority_50()
        st.dataframe(
            top_50[["CustomerID", "RFM_Segment", "CLV_Tier", "Churn_Risk_Band",
                     "predicted_clv", "churn_probability", "priority_score"]],
            use_container_width=True,
        )
    except:
        st.info("Run analysis first.")

    # --- Master Table (filterable) ---
    st.subheader("📊 Master Customer Table")
    filter_col1, filter_col2, filter_col3 = st.columns(3)
    with filter_col1:
        seg_filter = st.multiselect("RFM Segment", master["RFM_Segment"].unique(), default=master["RFM_Segment"].unique())
    with filter_col2:
        clv_filter = st.multiselect("CLV Tier", ["Platinum", "Gold", "Silver", "Bronze"], default=["Platinum", "Gold", "Silver", "Bronze"])
    with filter_col3:
        churn_filter = st.multiselect("Churn Risk", ["Low", "Medium", "High", "Critical"], default=["Low", "Medium", "High", "Critical"])

    filtered = master[
        (master["RFM_Segment"].isin(seg_filter)) &
        (master["CLV_Tier"].isin(clv_filter)) &
        (master["Churn_Risk_Band"].isin(churn_filter))
    ]
    st.write(f"Showing {len(filtered):,} of {len(master):,} customers")
    st.dataframe(filtered, use_container_width=True)

    st.download_button(
        "📥 Download Master Table",
        master.to_csv(index=False),
        "master_customer_table.csv",
        "text/csv",
    )
